<?xml version="1.0" encoding="UTF-8"?>

<!--
  * conferenceSettings.xml
  *
  * Copyright (c) 2003-2005 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default conference settings.
  *
  * $Id$
  -->

<!DOCTYPE conference_settings [
	<!ELEMENT conference_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<conference_settings>
	<setting type="bool">
		<name>showSetupHints</name>
		<value>true</value>
	</setting>
	<setting type="int">
		<name>numPageLinks</name>
		<value>10</value>
	</setting>
	<setting type="int">
		<name>itemsPerPage</name>
		<value>25</value>
	</setting>
	<setting type="string">
		<name>privacyStatement</name>
		<value>{translate key="default.conferenceSettings.privacyStatement"}</value>
	</setting>
	<setting type="string">
		<name>openAccessPolicy</name>
		<value>{translate key="default.conferenceSettings.openAccessPolicy"}</value>
	</setting>
	<setting type="string">
		<name>authorSelfArchivePolicy</name>
		<value>{translate key="default.conferenceSettings.authorSelfArchivePolicy"}</value>
	</setting>
	<setting type="string">
		<name>emailSignature</name>
		<value>{translate key="default.conferenceSettings.emailSignature"}</value>
	</setting>
	<setting type="string">
		<name>readerInformation</name>
		<value>{translate key="default.conferenceSettings.forReaders"}</value>
	</setting>
	<setting type="string">
		<name>authorInformation</name>
		<value>{translate key="default.conferenceSettings.forAuthors"}</value>
	</setting>
	<setting type="string">
		<name>lockssLicense</name>
		<value>{translate key="default.conferenceSettings.lockssLicense"}</value>
	</setting>

	<setting type="string">
		<name>primaryLocale</name>
		<value>{$primaryLocale}</value>
	</setting>

	<setting type="object">
		<name>submissionChecklist</name>
		<value>
			<array>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.notPreviouslyPublished"}</element>
						<element key="order">1</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.fileFormat"}</element>
						<element key="order">2</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.addressesLinked"}</element>
						<element key="order">3</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.submissionAppearance"}</element>
						<element key="order">4</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.bibliographicRequirements"}</element>
						<element key="order">5</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.anonymous"}</element>
						<element key="order">6</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.conferenceSettings.checklist.personalInformationRemoved"}</element>
						<element key="order">7</element>
					</array>
				</element>
			</array>
		</value>
	</setting>

	<setting type="bool">
		<name>rtAbstract</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtCaptureCite</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtViewMetadata</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtSupplementaryFiles</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtPrinterFriendly</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtAuthorBio</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtDefineTerms</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtAddComment</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtEmailAuthor</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtEmailOthers</name>
		<value>true</value>
	</setting>
</conference_settings>
