<?xml version="1.0" encoding="UTF-8"?>

<!--
  * schedConfSettings.xml
  *
  * Copyright (c) 2003-2005 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default scheduled conference settings.
  *
  * $Id$
  -->

<!DOCTYPE sched_conf_settings [
	<!ELEMENT sched_conf_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<sched_conf_settings>

	<!-- Review settings -->
	<setting type="int">
		<name>numWeeksPerReview</name>
		<value>4</value>
	</setting>

	<!-- Policy and default settings -->
	<setting type="string">
		<name>emailSignature</name>
		<value>{translate key="default.schedConfSettings.emailSignature"}</value>
	</setting>

</sched_conf_settings>
