<?xml version="1.0" encoding="UTF-8"?>
<!--
  * version.xml
  *
  * Copyright (c) 2000-2007 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * OCS version information.
  *
  * $Id$
  -->

<!DOCTYPE version [
	<!ELEMENT version (application, release, tag, date, info, package, patch*)>
	<!ELEMENT application (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT tag (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT info (#PCDATA)>
	<!ELEMENT package (#PCDATA)>
	<!ELEMENT patch (#PCDATA)>
		<!ATTLIST patch
			from CDATA #REQUIRED>
]>

<version>
	<application>ocs2</application>
	<release>2.1.0.0</release>
	<tag>ocs-2_1_0-0</tag>
	<date>2008-03-31</date>
	<info>http://pkp.sfu.ca/ocs/</info>
	<package>http://pkp.sfu.ca/ocs/download/ocs-2.1.0-0.tar.gz</package>
</version>
